### ISSUE TITLE
FireMonkey Compatibility

### ISSUE THREAD

**Issue by erosman** [adisloom/rufuker#1]
> It may also work in other usercript manager plugins like GreaseMonkey, ViolentMonkey, except for FireMonkey.

At a glance, I don't see any reason why it shouldn't.

### Notes
Since it is tested to work with Tampermonkey and it has `@grant        none`, TM injects the code into `page` context.

:pushpin:  If the code has to run in `page` context:
- Greasemonkey doesn't have a method to inject into `page` context, so for GM, it has to be done manually with `document.createElement('script')`
- FireMonkey and Violentmonkey can inject into `page` context with `@inject-into page`
- If the target site has strict CSP, FM|GM|VM can not inject into `page` context. TM alters site's CSP in order to inject into `page` context. However, `2ch.hk` & `2ch.pm` do not appear to have strict CSP.

**Comment by adisloom** [comment]
Yes, it finally works with Firemonkey. I've just tested. Thank you for pointing this out.
